export const users = [
  {
    id: "1",
    firstName: "Susil",
    lastName: "Prem",
    email: "sus@hgg.com",
    dateOfBirth: "2003/01/01",
    mobile: "0772004353",
    status: "offline",
    password: "",
    accountType: "admin",
  },
  {
    id: "2",
    firstName: "Ranil",
    lastName: "Nil",
    email: "ranil@hgg.com",
    dateOfBirth: "2003/01/01",
    mobile: "0773004353",
    status: "active",
    password: "",
    accountType: "student",
  },
  {
    id: "3",
    firstName: "Nimal",
    lastName: "Red",
    email: "nil@hgg.com",
    dateOfBirth: "2004/01/01",
    mobile: "0772004353",
    status: "active",
    password: "",
    accountType: "student",
  },
];
